In [ ]:
import tensorflow
model =tensorflow.keras.models.load_model(r'/content/my_model_train_71_test_23.h5')

In [ ]:
X_train.values[0]

array([1, 1, 0, 0, 0, 0, 0])

In [ ]:
model.predict(np.array([1, 1, 0, 0, 0, 0, 0]).reshape(1,-1))

1/1 [==============================] - 3s 3s/step


array([[4.2133197e-06, 3.0653283e-08, 1.1955078e-08, 3.5534686e-05,
        1.8096961e-10, 4.1698502e-05, 2.3450641e-09, 1.5130666e-11,
        8.1413296e-12, 1.0085306e-12, 1.4243537e-06, 9.9989843e-01,
        4.2881135e-10, 1.8638162e-05]], dtype=float32)

In [ ]:
import pandas as pd
df1=pd.read_csv("train.csv")
df2 = pd.read_csv("test.csv")
frames = [df1, df2]
df = pd.concat(frames)

In [ ]:
df

diabeties  hypertension  glaucoma  diabetic retinopathy  high myopia  \
0           0             0         0                     0            0   
1           1             0         0                     0            0   
2           1             1         0                     0            0   
3           1             1         1                     0            0   
4           1             1         1                     1            0   
..        ...           ...       ...                   ...          ...   
9           1             1         1                     1            1   
10          1             1         1                     1            1   
11          1             1         1                     1            1   
12          1             1         1                     1            1   
13          1             1         1                     1            1   

    sickle cell anemia  aids                 complication  
0                    0     0                          nil  
1                    0     0    Suprachoroidal Hemorrhage  
2                    0     0    Suprachoroidal Hemorrhage  
3                    0     0    Suprachoroidal Hemorrhage  
4                    0     0                Retinal Tears  
..                 ...   ...                          ...  
9                    1     0  Posterior Capsule Rupture\n  
10                   1     0      Cystoid Macular Edema\n  
11                   1     0            Endophthalmitis\n  
12                   1     0              Retinal Tears\n  
13                   1     1  Suprachoroidal Hemorrhage\n  

[193 rows x 8 columns]

In [ ]:
X=df.drop("complication",axis=1)
y=df['complication']

In [ ]:
y

0                             nil
1       Suprachoroidal Hemorrhage
2       Suprachoroidal Hemorrhage
3       Suprachoroidal Hemorrhage
4                   Retinal Tears
                 ...             
9     Posterior Capsule Rupture\n
10        Cystoid Macular Edema\n
11              Endophthalmitis\n
12                Retinal Tears\n
13    Suprachoroidal Hemorrhage\n
Name: complication, Length: 193, dtype: object

In [ ]:
pip install category_encoders

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.2/81.2 KB 9.1 MB/s eta 0:00:00


In [ ]:
from category_encoders import TargetEncoder
encoder = TargetEncoder()

In [ ]:
from sklearn import preprocessing

In [ ]:
le = preprocessing.LabelEncoder()

In [ ]:
output = le.fit_transform(y)

In [ ]:
y

0                             nil
1       Suprachoroidal Hemorrhage
2       Suprachoroidal Hemorrhage
3       Suprachoroidal Hemorrhage
4                   Retinal Tears
                 ...             
9     Posterior Capsule Rupture\n
10        Cystoid Macular Edema\n
11              Endophthalmitis\n
12                Retinal Tears\n
13    Suprachoroidal Hemorrhage\n
Name: complication, Length: 193, dtype: object

In [ ]:
li = ['nil', 'supras']

In [ ]:
import joblib

# Suppose enc is the trained encoder
joblib.dump(le, 'Labelencoder.pkl')

['Labelencoder.pkl']

In [ ]:
# Load the encoder from the saved file
loaded_encoder = joblib.load('Labelencoder.pkl')


In [ ]:
original_labels = loaded_encoder.inverse_transform(output)

In [ ]:
original_labels

array(['nil', 'Suprachoroidal Hemorrhage', 'Suprachoroidal Hemorrhage',
       'Suprachoroidal Hemorrhage', 'Retinal Tears',
       'Suprachoroidal Hemorrhage', 'Suprachoroidal Hemorrhage\n',
       'Retinal Tears', 'Suprachoroidal Hemorrhage\n',
       'Posterior Capsule Rupture\n', 'Cystoid Macular Edema\n',
       'Endophthalmitis\n', 'Retinal Tears\n',
       'Suprachoroidal Hemorrhage\n', 'Posterior Capsule Rupture\n',
       'Cystoid Macular Edema\n', 'Endophthalmitis', 'Retinal Tears\n',
       'Cystoid Macular Edema', 'Posterior Capsule Rupture',
       'Posterior Capsule Rupture', 'Suprachoroidal Hemorrhage',
       'Endophthalmitis', 'Endophthalmitis', 'Posterior Capsule Rupture',
       'Posterior Capsule Rupture', 'Posterior Capsule Rupture',
       'Posterior Capsule Rupture', 'Endophthalmitis',
       'Posterior Capsule Rupture', 'Endophthalmitis',
       'Posterior Capsule Rupture', 'Retinal tears',
       'Suprachoroidal Hemorrhage', 'Posterior Capsule Rupture',
       

In [ ]:
output

array([13, 11, 11, 11,  8, 11, 12,  8, 12,  6,  1,  4,  9, 12,  6,  1,  3,
        9,  0,  5,  5, 11,  3,  3,  5,  5,  5,  5,  3,  5,  3,  5, 10, 11,
        5,  3,  0,  5,  3,  0, 10,  5,  3, 10,  5,  3, 10, 11,  3, 10, 11,
        3, 10,  5,  5, 11,  5,  3,  5,  3,  5,  0,  5,  0, 11,  5,  0,  3,
        5,  0,  3,  7, 11, 10,  5,  2,  5,  2, 11,  3,  3, 11,  5,  5,  3,
        3, 10,  5,  5,  5,  5,  3, 10,  5,  3, 10,  3,  7, 11, 10,  5,  5,
        5,  3, 11,  5,  3, 11,  5,  3, 11, 10,  3, 10,  3,  3,  5,  0, 11,
        5,  0, 10, 11,  5,  0, 11,  5, 11, 11, 10,  5, 11, 10,  5, 11, 12,
        6,  1,  4, 12,  6,  1,  4, 10,  3, 10, 11,  3, 11,  3, 10, 11,  6,
        1, 10, 11,  6,  1,  3,  6,  1, 11, 11,  1,  6,  3, 10, 10,  3,  6,
       11, 13, 11, 11, 11, 10, 10,  6,  6, 13, 11, 11, 11,  8, 11, 12,  8,
       12,  6,  1,  4,  9, 12])

In [ ]:
original_labels = le.inverse_transform(output)

In [ ]:
len(set(output))

14

In [ ]:
!pip install tensorflow

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import tensorflow as tf

print(tf.__version__)


2.11.0


In [ ]:
from keras.utils import to_categorical
from sklearn.model_selection import train_test_split

In [ ]:
output2 = to_categorical(output)

In [ ]:
import numpy as np

In [ ]:
original_labels = np.argmax(output2, axis=1)

In [ ]:
original_labels

array([13, 11, 11, 11,  8, 11, 12,  8, 12,  6,  1,  4,  9, 12,  6,  1,  3,
        9,  0,  5,  5, 11,  3,  3,  5,  5,  5,  5,  3,  5,  3,  5, 10, 11,
        5,  3,  0,  5,  3,  0, 10,  5,  3, 10,  5,  3, 10, 11,  3, 10, 11,
        3, 10,  5,  5, 11,  5,  3,  5,  3,  5,  0,  5,  0, 11,  5,  0,  3,
        5,  0,  3,  7, 11, 10,  5,  2,  5,  2, 11,  3,  3, 11,  5,  5,  3,
        3, 10,  5,  5,  5,  5,  3, 10,  5,  3, 10,  3,  7, 11, 10,  5,  5,
        5,  3, 11,  5,  3, 11,  5,  3, 11, 10,  3, 10,  3,  3,  5,  0, 11,
        5,  0, 10, 11,  5,  0, 11,  5, 11, 11, 10,  5, 11, 10,  5, 11, 12,
        6,  1,  4, 12,  6,  1,  4, 10,  3, 10, 11,  3, 11,  3, 10, 11,  6,
        1, 10, 11,  6,  1,  3,  6,  1, 11, 11,  1,  6,  3, 10, 10,  3,  6,
       11, 13, 11, 11, 11, 10, 10,  6,  6, 13, 11, 11, 11,  8, 11, 12,  8,
       12,  6,  1,  4,  9, 12])

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, output2, test_size=0.4, random_state=0)

In [ ]:
y_test

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [ ]:
output2

array([[0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]], dtype=float32)

In [ ]:
import tensorflow as tf
from tensorflow.keras.applications.resnet_v2 import ResNet50V2
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.models import Model

resnet_model = ResNet50V2(input_shape=(X.shape[1],))


x = Dense(128, activation='relu')(x)
predictions = Dense(len(set(y)), activation='softmax')(x)

model = Model(inputs=resnet_model.input, outputs=predictions)

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

model.fit(X_train, y_train, epochs=100, batch_size=128, validation_split=0.2)

loss, accuracy = model.evaluate(X_test, y_test)
print("Model accuracy:", accuracy)


ValueError: ignored

In [ ]:
from tensorflow.keras.optimizers import Adam
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense



# Define the neural network architecture
model = Sequential()
model.add(Dense(64, activation='relu', input_shape=(X.shape[1],)))
model.add(Dense(92, activation='relu'))
model.add(Dense(153, activation='relu'))
model.add(Dense(285, activation='relu'))
model.add(Dense(375, activation='relu'))
model.add(Dense(285, activation='relu'))
model.add(Dense(153, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(32, activation='relu'))

model.add(Dense(len(set(y)), activation='softmax'))

# Compile the model
model.compile(optimizer=Adam(lr=0.001), loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(X_train,y_train, epochs=5000, batch_size=124, validation_split=0.2)

# Evaluate the model on the testing set
loss, accuracy = model.evaluate(X_test, y_test)
print("Model accuracy:", accuracy)

Streaming output truncated to the last 5000 lines.
Epoch 2502/5000
1/1 [==============================] - 0s 60ms/step - loss: 0.4976 - accuracy: 0.7065 - val_loss: 13.9863 - val_accuracy: 0.2609
Epoch 2503/5000
1/1 [==============================] - 0s 64ms/step - loss: 0.4976 - accuracy: 0.7065 - val_loss: 14.0331 - val_accuracy: 0.2609
Epoch 2504/5000
1/1 [==============================] - 0s 49ms/step - loss: 0.4978 - accuracy: 0.7065 - val_loss: 13.9773 - val_accuracy: 0.3043
Epoch 2505/5000
1/1 [==============================] - 0s 51ms/step - loss: 0.4978 - accuracy: 0.7065 - val_loss: 14.0313 - val_accuracy: 0.2609
Epoch 2506/5000
1/1 [==============================] - 0s 73ms/step - loss: 0.4977 - accuracy: 0.7065 - val_loss: 14.0185 - val_accuracy: 0.2609
Epoch 2507/5000
1/1 [==============================] - 0s 58ms/step - loss: 0.4976 - accuracy: 0.7065 - val_loss: 14.0177 - val_accuracy: 0.2609
Epoch 2508/5000
1/1 [==============================] - 0s 52ms/step - loss: 0.4

In [ ]:
from tensorflow.keras.layers import Input, Dense, Activation, Add
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam
def res_block(x, filters, block_num):
    # Define a residual block with skip connections
    y = Dense(filters, activation='relu', name=f'res{block_num}_a')(x)
    y = Dense(filters, activation='relu', name=f'res{block_num}_c')(y)
    y = Dense(filters, activation='relu', name=f'res{block_num}_b')(y)
    y = Add(name=f'res{block_num}_add')([x, y])
    y = Activation('relu', name=f'res{block_num}_out')(y)
    return y

inputs = Input(shape=(X.shape[1],))
x = Dense(164, activation='relu')(inputs)
x = res_block(x, 164, 1)
x = res_block(x, 164, 2)
x = res_block(x, 164, 3)
x = Dense(len(set(y)), activation='softmax')(x)

model = Model(inputs=inputs, outputs=x)

# Compile the model
model.compile(optimizer=Adam(lr=0.01), loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model
history = model.fit(X_train, y_train, epochs=5000, batch_size=32)

# Evaluate the model
loss, accuracy = model.evaluate(X_test, y_test)
print("Model accuracy:", accuracy)



Streaming output truncated to the last 5000 lines.
Epoch 2502/5000
4/4 [==============================] - 0s 11ms/step - loss: 0.6097 - accuracy: 0.6348
Epoch 2503/5000
4/4 [==============================] - 0s 11ms/step - loss: 0.6085 - accuracy: 0.6435
Epoch 2504/5000
4/4 [==============================] - 0s 10ms/step - loss: 0.6079 - accuracy: 0.6522
Epoch 2505/5000
4/4 [==============================] - 0s 10ms/step - loss: 0.6072 - accuracy: 0.6435
Epoch 2506/5000
4/4 [==============================] - 0s 11ms/step - loss: 0.6079 - accuracy: 0.6522
Epoch 2507/5000
4/4 [==============================] - 0s 12ms/step - loss: 0.6087 - accuracy: 0.6522
Epoch 2508/5000
4/4 [==============================] - 0s 11ms/step - loss: 0.6094 - accuracy: 0.6348
Epoch 2509/5000
4/4 [==============================] - 0s 11ms/step - loss: 0.6087 - accuracy: 0.6522
Epoch 2510/5000
4/4 [==============================] - 0s 11ms/step - loss: 0.6097 - accuracy: 0.6435
Epoch 2511/5000
4/4 [==========

In [ ]:
model.save('my_model_train_71_test_23.h5')

In [ ]:
from keras.layers import LeakyReLU




In [ ]:
from keras.models import load_model

model = load_model('model.h5')

OSError: ignored

In [ ]:
pip install lazypredict

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
from Lazypredict.Supervised Import LazyClassifier 

Xtrain, X_test, y_train, y_test= train_test_split(x,y,test size 5, random_state=223)

clf=LazyClassifier(verbose, ignore warnings True, custom_metricelione)

models.predictions clf.fittx train, test, y train, y.test)

print(models)

SyntaxError: ignored

In [ ]:
from lazypredict.Supervised import LazyClassifier
clf=LazyClassifier(verbose=0,ignore_warnings =True,custom_metric=None)
predictions = clf.fit(X_train,X_test,y_train,y_test)
print(predictions)

In [ ]:
##### Step 1 - Select data for modeling



##### Step 2 - Create training and testing samples
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)


##### Step 3 - Specify the structure of a Neural Network
model = Sequential(name="Model-with-One-Input") # Model
#model.add(Input(shape=(1,8), name='Input-Layer')) # Input Layer - need to speicfy the shape of inputs4
model.add(Dense(8))
model.add(Dense(2, activation='relu', name='Hidden-Layer'))
model.add(Dense(2, activation='relu', name='Hidden-Layer1'))
model.add(Dense(2, activation='relu', name='Hidden-Layer2'))
model.add(Dense(2, activation='relu', name='Hidden-Layer3'))
model.add(Dense(2, activation='relu', name='Hidden-Layer4'))
model.add(Dense(2, activation='relu', name='Hidden-Layer5'))
model.add(Dense(2, activation='relu', name='Hidden-Layer6'))
model.add(Dense(2, activation='relu', name='Hidden-Layer7')) # Hidden Layer, softplus(x) = log(exp(x) + 1)
model.add(Dense(1, activation='sigmoid', name='Output-Layer')) # Output Layer, sigmoid(x) = 1 / (1 + exp(-x))


##### Step 4 - Compile keras model
model.compile(optimizer='adam', # default='rmsprop', an algorithm to be used in backpropagation
              loss='binary_crossentropy', # Loss function to be optimized. A string (name of loss function), or a tf.keras.losses.Loss instance.
              metrics=['Accuracy', 'Precision', 'Recall'], # List of metrics to be evaluated by the model during training and testing. Each of this can be a string (name of a built-in function), function or a tf.keras.metrics.Metric instance. 
              loss_weights=None, # default=None, Optional list or dictionary specifying scalar coefficients (Python floats) to weight the loss contributions of different model outputs.
              weighted_metrics=None, # default=None, List of metrics to be evaluated and weighted by sample_weight or class_weight during training and testing.
              run_eagerly=None, # Defaults to False. If True, this Model's logic will not be wrapped in a tf.function. Recommended to leave this as None unless your Model cannot be run inside a tf.function.
              steps_per_execution=None # Defaults to 1. The number of batches to run during each tf.function call. Running multiple batches inside a single tf.function call can greatly improve performance on TPUs or small models with a large Python overhead.
             )


##### Step 5 - Fit keras model on the dataset
model.fit(X_train, # input data
          y_train, # target data
          batch_size=10, # Number of samples per gradient update. If unspecified, batch_size will default to 32.
          epochs=10000, # default=1, Number of epochs to train the model. An epoch is an iteration over the entire x and y data provided
          verbose='auto', # default='auto', ('auto', 0, 1, or 2). Verbosity mode. 0 = silent, 1 = progress bar, 2 = one line per epoch. 'auto' defaults to 1 for most cases, but 2 when used with ParameterServerStrategy.
          callbacks=None, # default=None, list of callbacks to apply during training. See tf.keras.callbacks
          validation_split=0.2, # default=0.0, Fraction of the training data to be used as validation data. The model will set apart this fraction of the training data, will not train on it, and will evaluate the loss and any model metrics on this data at the end of each epoch. 
          #validation_data=(X_test, y_test), # default=None, Data on which to evaluate the loss and any model metrics at the end of each epoch. 
          shuffle=True, # default=True, Boolean (whether to shuffle the training data before each epoch) or str (for 'batch').
          class_weight={0 : 0.3, 1 : 0.7}, # default=None, Optional dictionary mapping class indices (integers) to a weight (float) value, used for weighting the loss function (during training only). This can be useful to tell the model to "pay more attention" to samples from an under-represented class.
          sample_weight=None, # default=None, Optional Numpy array of weights for the training samples, used for weighting the loss function (during training only).
          initial_epoch=0, # Integer, default=0, Epoch at which to start training (useful for resuming a previous training run).
          steps_per_epoch=None, # Integer or None, default=None, Total number of steps (batches of samples) before declaring one epoch finished and starting the next epoch. When training with input tensors such as TensorFlow data tensors, the default None is equal to the number of samples in your dataset divided by the batch size, or 1 if that cannot be determined. 
          validation_steps=None, # Only relevant if validation_data is provided and is a tf.data dataset. Total number of steps (batches of samples) to draw before stopping when performing validation at the end of every epoch.
          validation_batch_size=None, # Integer or None, default=None, Number of samples per validation batch. If unspecified, will default to batch_size.
          validation_freq=3, # default=1, Only relevant if validation data is provided. If an integer, specifies how many training epochs to run before a new validation run is performed, e.g. validation_freq=2 runs validation every 2 epochs.
          max_queue_size=10, # default=10, Used for generator or keras.utils.Sequence input only. Maximum size for the generator queue. If unspecified, max_queue_size will default to 10.
          workers=1, # default=1, Used for generator or keras.utils.Sequence input only. Maximum number of processes to spin up when using process-based threading. If unspecified, workers will default to 1.
          use_multiprocessing=False, # default=False, Used for generator or keras.utils.Sequence input only. If True, use process-based threading. If unspecified, use_multiprocessing will default to False. 
         )


##### Step 6 - Use model to make predictions
# Predict class labels on training data
pred_labels_tr = (model.predict(X_train) > 0.5).astype(int)
# Predict class labels on a test data
pred_labels_te = (model.predict(X_test) > 0.5).astype(int)


##### Step 7 - Model Performance Summary
print("")
print('-------------------- Model Summary --------------------')
model.summary() # print model summary
print("")
print('-------------------- Weights and Biases --------------------')
for layer in model.layers:
    print("Layer: ", layer.name) # print layer name
    print("  --Kernels (Weights): ", layer.get_weights()[0]) # weights
    print("  --Biases: ", layer.get_weights()[1]) # biases
    
print("")
print('---------- Evaluation on Training Data ----------')
print(classification_report(y_train, pred_labels_tr))
print("")

print('---------- Evaluation on Test Data ----------')
print(classification_report(y_test, pred_labels_te))
print("")

UnimplementedError: ignored

In [ ]:
lr_model.predict([1,1,1,0,0,0,0]);

NameError: ignored